In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

In [11]:
cols = ["Algebra", "Adv Math", "PsDA", "Geometry", "Ez", "Medium", "Hard"]
df = pd.read_csv(r"C:\Users\phana\PycharmProjects\DataGen\datanew.csv", names=cols)    
#sep = seperator ( any spaces will be recognized as seperator )

In [12]:
df.head()

   Algebra  Adv Math  PsDA  Geometry    Ez  Medium  Hard
0     0.90      0.71  0.56      0.89  0.81    0.50  1.00
1     0.90      0.76  0.78      0.67  0.75    0.50  0.92
2     0.48      0.95  0.89      0.78  0.63    0.69  0.75
3     0.52      0.95  0.78      0.44  0.88    0.50  0.83
4     0.71      1.00  0.89      0.44  0.81    0.75  0.83

In [13]:
a = "Ez"
b = "Medium"
c = "Hard"

X = df[[a,b,c]].values

In [14]:
kmeans = KMeans(n_clusters=12).fit(X)

c:\Users\phana\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\phana\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=8.
  warnings.warn(

In [15]:
labels = kmeans.labels_

In [16]:
df['diff%'] = labels

In [17]:
df.head()

   Algebra  Adv Math  PsDA  Geometry    Ez  Medium  Hard  diff%
0     0.90      0.71  0.56      0.89  0.81    0.50  1.00      7
1     0.90      0.76  0.78      0.67  0.75    0.50  0.92      7
2     0.48      0.95  0.89      0.78  0.63    0.69  0.75      0
3     0.52      0.95  0.78      0.44  0.88    0.50  0.83      5
4     0.71      1.00  0.89      0.44  0.81    0.75  0.83      8

In [18]:
df.to_csv('datanew03.csv', index=False)